name: .github/workflows/flutter-nightly-byme.yml

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"